name: dart_api
version: 0.1.0
author: Kevin Segaud <segaud.kevin@gmail.com>
description: Team panda dart api
homepage: https://github.com/TeamDevPanda/dart_api
environment:
  sdk: '>=1.8.3 <2.0.0'
dependencies:
  crypto: any
  rpc: 0.3.0
  logging: any
  logging_handlers: any
  mongo_dart: any