name: dart_api
version: 0.1.0
author: Kevin Segaud <segaud.kevin@gmail.com>
description: Team panda dart api
homepage:
environment:
  sdk: '>=1.8.3 <2.0.0'
dependencies:
  rpc: 0.3.0
  logging: any
  logging_handlers: any